apiVersion: v1
kind: Service
metadata:
  name: file-upload
  labels:
    app: file-upload
spec:
  type: NodePort
  ports:
    - name: file-upload-http
      port: 8080
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
  selector:
    app: file-upload